-- KodingIoT Database Schema
-- PostgreSQL — Database: coding_iot

-- =============================================
-- 1. Create the database (run this separately as superuser)
-- =============================================
-- CREATE DATABASE coding_iot;

-- =============================================
-- 2. Users table
-- =============================================
CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    username    VARCHAR(50)  UNIQUE NOT NULL,
    email       VARCHAR(255) UNIQUE NOT NULL,
    password    VARCHAR(255) NOT NULL,           -- bcrypt hash
    role        VARCHAR(20)  NOT NULL DEFAULT 'student',  -- student | teacher | admin
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =============================================
-- 3. Projects table
-- =============================================
CREATE TABLE IF NOT EXISTS projects (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT         NOT NULL DEFAULT '',
    tags            TEXT[]       NOT NULL DEFAULT '{}',     -- PostgreSQL array
    level           VARCHAR(20)  NOT NULL DEFAULT 'mudah',  -- mudah | menengah | sulit
    type            VARCHAR(20)  NOT NULL DEFAULT 'iot',    -- iot | game | sensor
    workspace_data  JSONB        NOT NULL DEFAULT '{}',     -- Blockly serialization
    code            TEXT         NOT NULL DEFAULT '',        -- generated JS
    is_featured     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_public       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =============================================
-- 4. Indexes
-- =============================================
CREATE INDEX IF NOT EXISTS idx_projects_user_id   ON projects (user_id);
CREATE INDEX IF NOT EXISTS idx_projects_is_public ON projects (is_public);
CREATE INDEX IF NOT EXISTS idx_projects_type      ON projects (type);
CREATE INDEX IF NOT EXISTS idx_projects_level     ON projects (level);
CREATE INDEX IF NOT EXISTS idx_projects_tags      ON projects USING GIN (tags);

-- =============================================
-- 5. Helper: auto-update updated_at
-- =============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE OR REPLACE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 6. Seed: default admin account (password = "admin123")
--    Hash generated by: password_hash('admin123', PASSWORD_BCRYPT)
-- =============================================
-- INSERT INTO users (username, email, password, role)
-- VALUES ('admin', 'admin@kodingiot.local', '$2y$10$REPLACE_WITH_REAL_HASH', 'admin')
-- ON CONFLICT (username) DO NOTHING;
